version: '2'

services:
  ubuntu:
    build: ./docker/ubuntu/
    links:
      - php
    volumes_from:
      - data

  nginx:
    build: ./docker/nginx/
    ports:
      - 8080:80
    links:
      - php
    volumes_from:
      - data

  php:
    build: ./docker/php/
    expose:
      - 9000
    volumes_from:
      - data

  composer:
    build: ./docker/composer/
    volumes_from:
      - data

  build-tools:
    build: ./docker/build-tools/
    volumes_from:
      - data

  data:
    image: php:7.0-fpm
    volumes:
      - /Users/mattbailey/Sites/strax/sites/site:/var/www
    command: "true"
