version: '2'

services:
  nginx:
    build: ./docker/nginx/
    ports:
      - 8080:80
    links:
      - php
    volumes_from:
      - app

  php:
    build: ./docker/php/
    expose:
      - 9000
    volumes_from:
      - app

  app:
    image: php:7.0-fpm
    volumes:
      - .:/var/www/html
    command: "true"
