version: '2'

services:
  nginx:
    build: ./config/nginx/
    links:
      - php
    ports:
      - 80:80
    volumes_from:
      - unison

  php:
    build:
      context: ./config/php/
      args:
        webrootdir: ${WEBROOT_DIR}
    volumes:
      - ~/.composer:/root/.composer
      - ~/.ssh:/root/.ssh
    volumes_from:
      - unison
    working_dir: ${APP_DIR}

  unison:
    build:
      context: ./config/unison
      args:
        webrootdir: ${WEBROOT_DIR}
        projectdir: ${PROJECT_DIR}
    ports:
      - 5000:5000
    volumes:
      - ${PROJECT_DIR}
