version: '2'

services:
  nginx:
    build: ./config/nginx/
    ports:
      - 8080:80
    depends_on:
      - php
    volumes_from:
      - data

  php:
    build: ./config/php/
    expose:
      - 9000
    volumes_from:
      - data

  data:
    build: ./config/php/
    volumes:
      - ../site:/var/www/html
      - ~/.composer:/root/.composer
      - ~/.ssh:/root/.ssh
    command: "true"
