version: '2'

services:
  nginx:
    build: ./config/nginx/
    ports:
      - 80:80
    links:
      - php
    volumes_from:
      - unison

  php:
    build: ./config/php/
    volumes:
      - ~/.composer:/root/.composer
      - ~/.ssh:/root/.ssh
    volumes_from:
      - unison
    working_dir: /Users/mpkb/Projects/personal/docker-lemp/site

  unison:
    build: ./config/unison
    environment:
      - UNISON_VERSION=2.48.3
      - UNISON_WORKING_DIR=/Users/mpkb/Projects/personal/docker-lemp
    ports:
      - 5000:5000
    volumes:
      - /Users/mpkb/Projects/personal/docker-lemp
    working_dir: /Users/mpkb/Projects/personal/docker-lemp
