version: '2'

services:
  nginx:
    build: ./config/nginx/
    container_name: ${PROJECT_NAME}-nginx
    links:
      - php7fpm
    ports:
      - 80:80
    volumes_from:
      - unison

  php7fpm:
    build:
      context: ./config/php7fpm/
      args:
        webrootdir: ${WEBROOT_DIR}
    container_name: php7fpm
    volumes:
      - ~/.composer:/root/.composer
      - ~/.ssh:/root/.ssh
    volumes_from:
      - unison
    working_dir: ${APP_DIR}

  unison:
    build:
      context: ./config/unison
      args:
        webrootdir: ${WEBROOT_DIR}
        projectdir: ${PROJECT_DIR}
    container_name: ${PROJECT_NAME}-unison
    ports:
      - 5000:5000
    volumes:
      - ${PROJECT_DIR}
