version: '2'

services:
  nginx:
    build: ./config/nginx/
    ports:
      - 8080:80
    links:
      - php
    volumes_from:
      - data

  php:
    build: ./config/php/
    expose:
      - 9000
    volumes_from:
      - data
    volumes:
      - "~/.composer:/root/.composer"
      - "~/.ssh:/root/.ssh"

  composer:
    build: ./config/composer/
    links:
      - php
    volumes_from:
      - data

  build-tools:
    build: ./config/build-tools/
    links:
      - php
    volumes_from:
      - data

  data:
    build: ./config/php/
    volumes:
      - ../site:/var/www/html
    command: "true"
