#!/bin/bash

if [ "$1" = "rebuild" ]; then
    cd docker && docker-compose build ; cd -
fi
! ifconfig | grep 172.16.123.1 && sudo ifconfig lo0 alias 172.16.123.1
cd docker
docker-compose up -d 
cd -
echo "Starting docker daemon for PHP Storm"
socat TCP-LISTEN:2375,reuseaddr,fork,bind=localhost UNIX-CONNECT:/var/run/docker.sock &
echo "Running filesystem sync process"
fswatch -o . | xargs -n1 -I{} unison . 'socket://localhost:5000/' -ignore 'Path {var,pub/static,.idea}' -ignore 'Name node_modules' -auto -batch
echo "Killing all socat processes"
killall socat
